[character]
success_symbol = "[âžœ](green) "
vicmd_symbol = "[V](green) "

[line_break]
disabled = true

[cmd_duration]
disabled = true

[directory]
style = 'bold cyan'

[git_branch]
symbol = ''
style = 'bold purple'

[git_status]
style = 'bold red'

[elixir]
format = "[ELIXIR $version](bold purple) "

[package]
disabled = true

[python]
disabled = true

[nodejs]
format = "[NODE $version](bold green) "

[ruby]
format = "[RUBY $version ](red bold)"

[rust]
disabled = true
