# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](green) "
vicmd_symbol = "[V](green) "

[line_break]
disabled = true

[cmd_duration]
disabled = true

[directory]
style = 'bold cyan'

[git_branch]
style = 'bold purple'

[git_status]
style = 'bold red'

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
format = "‒ [RUBY $version ](red bold)"

[rust]
disabled = true

# Color Bin

# style = 'bold #ff7c00' # Orange
# style = 'bold #8DD3BF' # Cyan...similar to OG directory but a little darker
# style = 'bold #CDADCD' # Light pink/purple
# style = 'bold #91A4E5' # Nice purple-ish blue
