[character]
success_symbol = "[âžœ](green) "
vicmd_symbol = "[V](green) "

[line_break]
disabled = true

[cmd_duration]
disabled = true

[directory]
style = 'bold cyan'

[git_branch]
style = 'bold purple'

[git_status]
style = 'bold red'

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
format = "[RUBY $version ](red bold)"

[rust]
disabled = true
